# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
variables:
   docker_username: 'praqmasofus'

pool:
  vmImage: 'ubuntu-latest'

stages:
      - stage: START
        jobs:
         - job: pipelinestart
           steps:
           - script: echo Pipeline to build , test and create Docker Image
             displayName: 'Started Pipeline'
           - script: echo $(System.DefaultWorkingDirectory) && echo $(Build.ArtifactStagingDirectory) && echo ($docker_username)
      - stage: 
        jobs:
         - job: BuildPipeline
           steps:
              - bash: ci/build-app.sh
                displayName: 'Build'
              - bash: ci/unit-test-app.sh
                displayName: 'Test'
              - bash: ci/build-docker.sh
                displayName: 'Docker Build'
              - bash: ci/push-docker.sh
                displayName: 'Docker Image Push'
              - bash: ci/component-test.sh
                displayName: 'Docker compose'
