# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
      - stage: START
        jobs:
         - job: pipelinestart
           steps:
           - script: echo Pipeline to build , test and create Docker Image
             displayName: 'Started Pipeline'
           - script: echo $(System.DefaultWorkingDirectory) && echo $(Build.ArtifactStagingDirectory)
      - stage: 
        jobs:
         - job: Build
           steps:
              - bash: ci/build-app.sh
                displayName: 'Build'
         - job: UnitTest
           steps:
              - bash: ci/unit-test-app.sh
                displayName: 'Test'
         - job: Dockerbuild
           steps: 
           - bash: ci/build-docker.sh
             displayName: 'Docker Build'
         - job: Dockerpush
           steps:
            - bash: ci/push-docker.sh
              displayName: 'Docker Image Push'
         - job: Dockercompose
           steps: 
            - bash: ci/component-test.sh
              displayName: 'Docker compose'
