# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
      - stage: START
        jobs:
         - job: pipelinestart
           steps:
           - script: echo Pipeline to build , test and create Docker Image
             displayName: 'Started Pipeline'

      stage: Build
        steps:
          - bash: ci/build-app.sh
            displayName: 'Build'

      stage: Test
        steps:
          - bash: ci/unit-test-app.sh
            displayName: 'Test'

      stage: Docker Build and Push
        steps: 
            - bash: ci/build-docker.sh
              displayName: 'Docker Build'

            - bash: ci/push-docker.sh
              displayName: 'Docker Image Push'

      stage: Docker Compose
        steps: 
            - bash: ci/component-test.sh
              displayName: 'Docker compose'
